#!/bin/bash
echo -e please tell us your login name
read name
grep "$name" /etc/passwd >1
if [ $? == 0 ]
then 
	echo -e found \<$name\> in the /etc/passwd file. 
else
	echo No such user on our system
fi
